---
name: Timber
version: 2.2.1
api:
- 5.0.0
main: Zonasky\KumaDev
author:
- Inaayat
- skyss0fly
description: Instantly chops down trees with Timber
website: 
- https://github.com/KumaaDev/Timber

...
