# Timber Config

# Specify the folder name of each world where Timber should work on.
worlds:
- world
- anotherworld

# Makes leaves chops aswell when chops down trees
leaves: true
maxLeafDrops: 10

# Actived Autopickup (true/false)
auto_pickup: true

# Actived OnlySneak (true/false)
onlysneak: true
